name: concious_consumer_duo_app
description: "Duo case Dirk and Wilson"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  native_barcode_scanner: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - images/ecoscore.png
  - images/milk.jpg
  - images/nutriscore.png
  - images/betterfor.gif
  - images/glutenfree.avif
  - images/weidemelk.png
  - images/vegan.png